
services:
  mysql-auth:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306" # Auth DB on host port 3306
    volumes:
      - auth-data:/var/lib/mysql

  mysql-account:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: account_db
    ports:
      - "3308:3306" # Account DB on host port 3307
    volumes:
      - account-data:/var/lib/mysql

  mysql-transaction:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: transaction_db
    ports:
      - "3309:3306" # Transaction DB on host port 3308
    volumes:
      - transaction-data:/var/lib/mysql

  mysql-notification:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: notification_db
    ports:
      - "3310:3306"  # Notification DB on host port 3310
    volumes:
      - notification-data:/var/lib/mysql

  naming-server:
    build:
      # Path to the naming-server project folder
      context: ./naming-server
    ports:
      # Map host port 8761 to container port 8761
#      - "8761:8761"
      - "8671:8671"

volumes:
  auth-data:
  account-data:
  transaction-data:
  notification-data: