version: '3.8'

services:
  mysql-auth:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306" # Auth DB on host port 3306
    volumes:
      - auth-data:/var/lib/mysql

  mysql-account:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: account_db
    ports:
      - "3308:3306" # Account DB on host port 3307
    volumes:
      - account-data:/var/lib/mysql

  mysql-transaction:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: transaction_db
    ports:
      - "3309:3306" # Transaction DB on host port 3308
    volumes:
      - transaction-data:/var/lib/mysql

volumes:
  auth-data:
  account-data:
  transaction-data: