server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**

            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**

            - id: transaction
              uri: lb://transaction
              predicates:
                - Path=/transaction/**

            - id: loan
              uri: lb://loan
              predicates:
                - Path=/loan/**

            - id: customers
              uri: lb://customers
              predicates:
                - Path=/customers/**

            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**

            - id: notification
              uri: lb://notification
              predicates:
                - Path=/notification/**

springdoc:
  swagger-ui:
    urls:
      - name: transaction
        url: /transaction/v3/api-docs
      - name: auth
        url: /auth/v3/api-docs
      - name: notification
        url: /notification/v3/api-docs
      - name: customers
        url: /customers/v3/api-docs
      - name: exchange
        url: /exchange/v3/api-docs
  override-server-url: true

jwt:
  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=
  expiration: 86400000 # 24 horas em ms

