server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**

            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**

            - id: transaction
              uri: lb://transaction
              predicates:
                - Path=/transaction/**

            - id: loan
              uri: lb://loan
              predicates:
                - Path=/loan/**

            - id: customers
              uri: lb://customers
              predicates:
                - Path=/customers/**

            - id: notifications
              uri: lb://notifications
              predicates:
                - Path=/notifications/**

            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**

springdoc:
  swagger-ui:
    urls:
      - name: transaction
        url: /transaction/v3/api-docs
      - name: auth
        url: /auth/v3/api-docs




