server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: Morteaolombok123
    key-store-type: PKCS12

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
#          globalcors:
#            corsConfigurations:
#              '[/**]':
#                allowedOrigins: "http://172.203.234.78:3000"
#                allowedMethods:
#                  - GET
#                  - POST
#                  - PUT
#                  - DELETE
#                  - OPTIONS
#                allowedHeaders: "*"
#                allowCredentials: true
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - JwtAuthenticationFilter

            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**

            - id: transaction
              uri: lb://transaction
              predicates:
                - Path=/transaction/**
              filters:
                - JwtAuthenticationFilter

            - id: loan
              uri: lb://loan
              predicates:
                - Path=/loan/**
              filters:
                - JwtAuthenticationFilter

            - id: customers
              uri: lb://customers
              predicates:
                - Path=/customers/**
              filters:
                - JwtAuthenticationFilter

            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**
              filters:
                - JwtAuthenticationFilter
            #              filters:
            #                - StripPrefix=1

            - id: notification
              uri: lb://notification
              predicates:
                - Path=/notification/**
              filters:
                - JwtAuthenticationFilter

            - id: card
              uri: lb://card
              predicates:
                - Path=/card/**
              filters:
                - JwtAuthenticationFilter

            - id: statement-service
              uri: lb://statement-service
              predicates:
                - Path=/statement-service/**
#              filters:
#                - AuthenticationFilter

            - id: investment
              uri: lb://investment
              predicates:
                - Path=/investment/**
#              filters:
#                - AuthenticationFilter


            - id: investment-crypto
              uri: lb://investment
              predicates:
                - Path=/crypto/**
#              filters:
#                - AuthenticationFilter

            - id: investment-stock
              uri: lb://investment
              predicates:
                - Path=/stock/**
#              filters:
#                - AuthenticationFilter

            - id: benefits
              uri: lb://benefits
              predicates:
                - Path=/benefits/**


springdoc:
  swagger-ui:
    urls:
      - name: transaction
        url: /transaction/v3/api-docs
      - name: auth
        url: /auth/v3/api-docs
      - name: notification
        url: /notification/v3/api-docs
      - name: customers
        url: /customers/v3/api-docs
      - name: exchange
        url: /exchange/v3/api-docs
      - name: card
        url: /card/v3/api-docs
      - name: statement-service
        url: /statement-service/v3/api-docs
      - name: investment
        url: /investment/v3/api-docs
      - name: benefits
        url: /benefits/v3/api-docs
  override-server-url: true

#jwt:
#  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=
#  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=
#  expiration: 86400000 # 24 horas em ms

jwt:
  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=

