server:
  port: 8300
spring:
  datasource:
    url: jdbc:mysql://localhost:3311/customer_db
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect