server:
  port: 8300
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3311/customer_db
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     # opcional: se quiser registrar pelo IP em vez de hostname
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health

springdoc:
  api-docs:
    path: /costumers/v3;api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /customers/v3/api/docs
override-server-url: true

management:
  health:
    rabbit:
      enabled: false