spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3310/notification_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: cicarusbank@gmail.com
    password: hugk nhwa treu tdqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false     # opcional: se quiser registrar pelo IP em vez de hostname
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health

management:
  health:
   rabbit:
     enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

