spring:
  application:
    name: notification
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  datasource:
    url: jdbc:mysql://localhost:3310/notification_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: cicarusbank@gmail.com
    password: hugk nhwa treu tdqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     # opcional: se quiser registrar pelo IP em vez de hostname
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health

management:
  health:
   rabbit:
     enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /notification/v3/api-docs
  swagger-ui:
    url: /notification/v3/api-docs
  override-server-url: true

jwt:
  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=
  expiration: 86400000 # 24 horas em ms