server:
  port: 8000
spring:
  application:
    name: auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Use the transaction DB port from docker-compose.yml
    url: jdbc:mysql://localhost:3307/auth_db
    username: root
    # Make sure this matches your docker-compose password
    password: 123
  jpa:
    hibernate:
      ddl-auto: none # This is correct for recreating the DB
    # Corrected indentation for these properties
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    logging:
      level:
        org.flywaydb.core: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     # opcional: se quiser registrar pelo IP em vez de hostname
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health

jwt:
  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=
  expiration: 86400000 # 24 horas em ms

logging:
  spring:
    security:
      debug: true
  level:
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    url: /auth/v3/api-docs
