server:
  port: ${PORT:8761}
spring:
  application:
    name: naming-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: https://naming-server-app.azurewebsites.net/eureka/
