-- INSERT INTO transaction (account_id, transaction_type, amount, timestamp) VALUES
--                                                                               (1, 'DEPOSIT', 100.50, NOW()),
--                                                                               (2, 'WITHDRAWAL', 50.25, NOW()),
--                                                                               (3, 'TRANSFER', 200.00, NOW()),
--                                                                               (1, 'DEPOSIT', 300.00, NOW() - INTERVAL 1 DAY),
--                                                                               (2, 'TRANSFER', 150.75, NOW() - INTERVAL 2 DAY),
--                                                                               (4, 'WITHDRAWAL', 75.00, NOW() - INTERVAL 3 DAY),
--                                                                               (5, 'DEPOSIT', 500.00, NOW() - INTERVAL 4 DAY),
--                                                                               (3, 'TRANSFER', 120.00, NOW() - INTERVAL 5 DAY),
--                                                                               (2, 'DEPOSIT', 80.80, NOW() - INTERVAL 6 DAY),
--                                                                               (1, 'WITHDRAWAL', 60.60, NOW() - INTERVAL 7 DAY);