spring:
  application:
    name: transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Use the transaction DB port from docker-compose.yml
    url: jdbc:mysql://localhost:3308/transaction_db
    username: root
    # Make sure this matches your docker-compose password
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop # This is correct for recreating the DB
    # Corrected indentation for these properties
    show-sql: true
    open-in-view: false