server:
  port: 8100
spring:
  application:
    name: transaction
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/transaction_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.flywaydb.core: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true     # opcional: se quiser registrar pelo IP em vez de hostname
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /transaction/v3/api-docs
  swagger-ui:
    url: /transaction/v3/api-docs
  override-server-url: true


#jwt:
#  secret: hzAS6BikJ_2Ft3fEye-lqwGviIeGbWFRG9mEnNDzQp4=
#  expiration: 86400000 # 24 horas em ms